// Alle understøttede kategorier med ikon, farve og formular-felter.

export const CATEGORIES = [
  {
    id: 'music',
    label: 'Musik',
    singular: 'Album',
    imageQuery: 'album cover',
    icon: '🎵',
    color: 'var(--cat-music)',
    placeholder: 'fx Dark Side of the Moon',
    ratingCategories: ['Sammenhæng/flow', 'Replay value', 'Produktion', 'Sangskrivning', 'Features'],
    hasTracks: true,
    imageFormat: { ratio: 1, outputSize: 3000 },
    cardFields: ['year'],
    cardImageRatio: '1/1',
    sortOptions: [
      { id: 'year', label: 'Udgivelsesår' },
    ],
    quickAddStatuses: ['Igangværende', 'Vil lytte'],
    statusTabs: [
      { label: 'Alle',       value: null },
      { label: 'I gang',     value: 'Igangværende' },
      { label: 'Afsluttet',  value: 'Afsluttet' },
      { label: 'Vil lytte',  value: 'Vil lytte' },
    ],
    fields: [
      { id: 'artist',      label: 'Kunstner',     type: 'text',   placeholder: 'fx Pink Floyd', required: true },
      { id: 'year',        label: 'Udgivelsesår', type: 'number', placeholder: 'fx 1973' },
      { id: 'genre',       label: 'Genre',         type: 'text',   placeholder: 'fx Progressiv rock' },
      { id: 'status',      label: 'Status',         type: 'select', options: ['Afsluttet', 'Igangværende', 'Vil lytte', 'Annulleret'] },
      { id: 'description', label: 'Beskrivelse',  type: 'textarea', placeholder: 'Dine tanker om albummet...' },
    ],
    subtitleField: 'artist',
  },
  {
    id: 'film',
    label: 'Film',
    singular: 'Film',
    imageQuery: 'movie poster',
    icon: '🎬',
    color: 'var(--cat-film)',
    placeholder: 'fx Inception',
    ratingCategories: ['Instruktion', 'Manuskript', 'Skuespil', 'Cinematografi', 'Soundtrack/lyd', 'Tempo/flow'],
    quickAddStatuses: ['Vil se'],
    statusTabs: [
      { label: 'Alle',   value: null },
      { label: 'Vil se', value: 'Vil se' },
      { label: 'Set',    value: 'Set' },
    ],
    fields: [
      { id: 'year',        label: 'Udgivelsesår', type: 'number', placeholder: 'fx 2010' },
      { id: 'genre',       label: 'Genre',         type: 'text',   placeholder: 'fx Thriller, sci-fi' },
      { id: 'status',      label: 'Status',         type: 'select', options: ['Set', 'Vil se'] },
      { id: 'description', label: 'Beskrivelse',  type: 'textarea', placeholder: 'Dine tanker om filmen...' },
    ],
    subtitleField: 'year',
  },
  {
    id: 'series',
    label: 'Serier',
    singular: 'Serie',
    imageQuery: 'tv series poster',
    icon: '📺',
    color: 'var(--cat-series)',
    placeholder: 'fx Breaking Bad',
    ratingCategories: ['Manuskript/skrivning', 'Skuespil', 'Instruktion', 'Soundtrack/lyd', 'Tempo', 'Replay value'],
    hasSeasons: true,
    quickAddStatuses: ['Igangværende', 'Vil se'],
    statusTabs: [
      { label: 'Alle',       value: null },
      { label: 'I gang',     value: 'Igangværende' },
      { label: 'Afsluttet',  value: 'Afsluttet' },
      { label: 'Vil se',     value: 'Vil se' },
    ],
    fields: [
      { id: 'creator',     label: 'Skaber',        type: 'text',   placeholder: 'fx Vince Gilligan', required: true },
      { id: 'year',        label: 'Startår',       type: 'number', placeholder: 'fx 2008' },
      { id: 'genre',       label: 'Genre',          type: 'text',   placeholder: 'fx Drama, krimi' },
      { id: 'status',      label: 'Status',         type: 'select', options: ['Afsluttet', 'Igangværende', 'Vil se', 'Annulleret'] },
      { id: 'description', label: 'Beskrivelse',   type: 'textarea', placeholder: 'Dine tanker om serien...' },
    ],
    subtitleField: 'creator',
  },
  {
    id: 'games',
    label: 'Spil',
    singular: 'Spil',
    imageQuery: 'game cover art',
    icon: '🎮',
    color: 'var(--cat-games)',
    placeholder: 'fx The Last of Us',
    ratingCategories: ['Gameplay', 'Historie/narrativ', 'Grafik/art direction', 'Soundtrack', 'Længde/indhold', 'Univers', 'Underholdning'],
    cardFields: ['year', 'dateFinished'],
    quickAddStatuses: ['Igangværende', 'Vil spille'],
    statusTabs: [
      { label: 'Alle',       value: null },
      { label: 'I gang',     value: 'Igangværende' },
      { label: 'Afsluttet',  value: 'Afsluttet' },
      { label: 'Vil spille', value: 'Vil spille' },
    ],
    sortOptions: [
      { id: 'year',         label: 'Udgivelsesår' },
      { id: 'dateFinished', label: 'Færdiggjort' },
    ],
    fields: [
      { id: 'developer',    label: 'Udvikler',            type: 'text',   placeholder: 'fx Naughty Dog', required: true },
      { id: 'year',         label: 'Udgivelsesår',        type: 'number', placeholder: 'fx 2013' },
      { id: 'dateFinished', label: 'Dato for afslutning', type: 'date' },
      { id: 'status',       label: 'Status',               type: 'select', options: ['Afsluttet', 'Igangværende', 'Vil spille', 'Annulleret'] },
      { id: 'description',  label: 'Beskrivelse',         type: 'textarea', placeholder: 'Dine tanker om spillet...' },
    ],
    subtitleField: 'developer',
  },
  {
    id: 'books',
    label: 'Bøger',
    singular: 'Bog',
    imageQuery: 'book cover',
    icon: '📚',
    color: 'var(--cat-books)',
    placeholder: 'fx 1984',
    ratingCategories: ['Fortælling', 'Karakterer', 'Skrivestil'],
    quickAddStatuses: ['Igangværende', 'Vil læse'],
    statusTabs: [
      { label: 'Alle',      value: null },
      { label: 'I gang',    value: 'Igangværende' },
      { label: 'Læst',      value: 'Afsluttet' },
      { label: 'Vil læse',  value: 'Vil læse' },
    ],
    fields: [
      { id: 'author',      label: 'Forfatter',    type: 'text',   placeholder: 'fx George Orwell', required: true },
      { id: 'year',        label: 'Udgivelsesår', type: 'number', placeholder: 'fx 1949' },
      { id: 'genre',       label: 'Genre',         type: 'text',   placeholder: 'fx Dystopisk fiktion' },
      { id: 'pages',       label: 'Sider',         type: 'number', placeholder: 'fx 328' },
      { id: 'status',      label: 'Status',         type: 'select', options: ['Afsluttet', 'Igangværende', 'Vil læse', 'Annulleret'] },
      { id: 'description', label: 'Beskrivelse',  type: 'textarea', placeholder: 'Dine tanker om bogen...' },
    ],
    subtitleField: 'author',
  },
  {
    id: 'podcasts',
    label: 'Podcasts',
    singular: 'Podcast',
    imageQuery: 'podcast cover artwork',
    icon: '🎙️',
    color: 'var(--cat-podcasts)',
    placeholder: 'fx Lex Fridman Podcast',
    cardImageRatio: '1/1',
    quickAddStatuses: ['Igangværende', 'Vil lytte'],
    statusTabs: [
      { label: 'Alle',      value: null },
      { label: 'I gang',    value: 'Igangværende' },
      { label: 'Afsluttet', value: 'Afsluttet' },
      { label: 'Vil lytte', value: 'Vil lytte' },
    ],
    fields: [
      { id: 'genre',       label: 'Kategori',      type: 'text',   placeholder: 'fx Teknologi, videnskab' },
      { id: 'status',      label: 'Status',         type: 'select', options: ['Afsluttet', 'Igangværende', 'Vil lytte', 'Annulleret'] },
      { id: 'description', label: 'Beskrivelse',   type: 'textarea', placeholder: 'Dine tanker om podcasten...' },
    ],
    subtitleField: 'genre',
  },
  {
    id: 'escape',
    label: 'Escape Rooms',
    singular: 'Escape Room',
    imageQuery: 'escape room',
    icon: '🔐',
    color: 'var(--cat-escape)',
    placeholder: 'fx The Lost Temple',
    ratingCategories: ['Puslespil', 'Tema/historie', 'Indretning', 'Atmosfære', 'Spilflow', 'Instruktør'],
    cardImageRatio: '1/1',
    quickAddStatuses: ['Vil prøve'],
    statusTabs: [
      { label: 'Alle',           value: null },
      { label: 'Vil prøve',      value: 'Vil prøve' },
      { label: 'Gennemført',     value: 'Gennemført' },
      { label: 'Ikke gennemført', value: 'Ikke gennemført' },
    ],
    fields: [
      { id: 'company',     label: 'Firma',           type: 'text', placeholder: 'fx Fox in a Box' },
      { id: 'city',        label: 'By',               type: 'text', placeholder: 'fx København' },
      { id: 'country',     label: 'Land',             type: 'text', placeholder: 'fx Danmark' },
      { id: 'datePlayed',  label: 'Dato for besøg',   type: 'date' },
      { id: 'status',      label: 'Status',            type: 'select', options: ['Gennemført', 'Ikke gennemført', 'Vil prøve'] },
      { id: 'description', label: 'Beskrivelse',      type: 'textarea', placeholder: 'Dine tanker om rummet...' },
    ],
    subtitleField: 'company',
  },
  {
    id: 'concerts',
    label: 'Koncerter',
    singular: 'Koncert',
    imageQuery: 'concert live performance',
    icon: '🎤',
    color: 'var(--cat-concerts)',
    placeholder: 'fx Eras Tour',
    ratingCategories: ['Lydkvalitet', 'Kunstnerens performance', 'Effekter', 'Oplevelsen', 'Spillestedet'],
    quickAddStatuses: ['Vil se'],
    statusTabs: [
      { label: 'Alle',   value: null },
      { label: 'Vil se', value: 'Vil se' },
      { label: 'Set',    value: 'Set' },
    ],
    fields: [
      { id: 'artist',      label: 'Kunstner',      type: 'text', placeholder: 'fx Taylor Swift', required: true },
      { id: 'venue',       label: 'Spillested',     type: 'text', placeholder: 'fx Royal Arena' },
      { id: 'city',        label: 'By',             type: 'text', placeholder: 'fx København' },
      { id: 'country',     label: 'Land',           type: 'text', placeholder: 'fx Danmark' },
      { id: 'status',      label: 'Status',          type: 'select', options: ['Set', 'Vil se'] },
      { id: 'description', label: 'Beskrivelse',   type: 'textarea', placeholder: 'Dine tanker om koncerten...' },
    ],
    subtitleField: 'artist',
  },
];

export function getCategoryById(id) {
  return CATEGORIES.find((c) => c.id === id) ?? null;
}

export function getSubtitle(item) {
  const cat = getCategoryById(item.category);
  if (!cat) return '';
  return item[cat.subtitleField] ?? '';
}
